### PR TITLE
(Closes #445) upgrade to v4 of codecov action and supply token

### LINKED ISSUE #445: Update to latest CodeCov uploader Action.
Uploads to CodeCov are failing and complaining about the lack of a token. We need to replicate https://github.com/stfc/PSyclone/pull/2549 here.

### PR DESCRIPTION
**Pull request by arporter**

### CODE REVIEW

**Comment by arporter** [comment]
I've added the CodeCov token to the list of 'secrets' for this repo.
Upload to CodeCov was performed successfully (although CodeCov is still not happy because there's no coverage report for the base commit of this PR). Landing page now has a pretty picture :-)
Ready for review from @sergisiso or @hiker.

**Review by sergisiso — CHANGES_REQUESTED** [review]
@arporter I am fine with the update to v4 but note that this does not fix the status check issue and still requires a merge without waiting to met the requirements. Note that v3 already provided report comments, so this doesn't change the behaviour. Should we try to fix it in this PR? But if you want this on master first I will be happy to approve.

**Comment by arporter** [comment]
Thanks @sergisiso. I've googled and can find nothing to suggest we're doing anything wrong. Before this patch, uploads to CodeCov were failing with a 'missing token' error. This at least fixes that. I've looked at the CodeCov github app and that seems fine. The upload to CodeCov is fine. It just seems that CodeCov is not then reporting back to GitHub, possibly because it says it's missing coverage for the base commit. Therefore, I think this can go on as it is a small improvement over what we currently have.

**Review by sergisiso — APPROVED** [review]
OK thanks @arporter, this is approved for merging.

**Pull request merged**
