### PR TITLE
Fparser2 pycodestyle issue #89

### PR DESCRIPTION
**Pull request by rupertford**
This PR makes fparser2 pycodestyle compliant. It makes no functional changes to fparser.

### CODE REVIEW

**Comment by rupertford** [comment]
I suspect that coverage has gone down as I have split a number of lines to make the code conformant. My guess is that this has resulted in more uncovered lines overall.

**Comment by TeranIvy** [comment]
Hi @rupertford. Yes, the coverage likely went down as the result of code improvements, I had the same problem in one of my PRs.

**Comment by rupertford** [comment]
Hi @TeranIvy, I've added you as a potential reviewer just in case you're keen :-)

**Comment by TeranIvy** [comment]
That'll teach me :) Taken.

**Comment by rupertford** [comment]
I've created issue #91 for pylint improvements to fparser2 as requested.

I agree with the reviewer that the code and tests should be split at some point, although the way Fortran2003.py works, with it statically creating a subclass dictionary, may cause complications. I think this is beyond the scope of this PR, although there is already issue #38 related to the structure of the tests. As the reviewer has requested it, I have created issue #92 to look at how we might want to restructure the fparser2 code (i.e. Fortran2003.py).

I think making it a rule to have to have full coverage of a class if it is modified would be OK for the "core" developers, but might put off contributions from others. Therefore I'm not sure it should be mandatory.

Hopefully this addresses the reviewers comments. Back to @TeranIvy

**Pull request merged**
