### PR TITLE
(Closes #350) disable validation checks by default

### LINKED ISSUE #350: Allow symbol checks to be disabled
The new symbol table functionality is somewhat immature (it cannot cope with use association) and only works if the supplied source is valid Fortran, even if any pre-processor directives are ignored. These limitations mean that it can be tripped up in certain circumstances. While support for use association is planned (#201 and #349), there's no plan to handle CPP directives. Therefore we will allow the checking performed by the symbol table to be disabled at run time.

I'm not sure whether this will be best done by completely disabling the symbol table functionality or by only disabling the checks that a symbol does not already exist.

### PR DESCRIPTION
**Pull request by arporter**

### CODE REVIEW

**Comment by arporter** [comment]
This is ready for review now.

**Comment by TeranIvy** [comment]
Tested in the LFRic suite. All green: PSycloning, compilation, runs, style checks and KGO checks.

**Comment by arporter** [comment]
> Tested in the LFRic suite. All green: PSycloning, compilation, runs, style checks and KGO checks.

Hi @TeranIvy, was that with HEAD of PSyclone master?

**Comment by TeranIvy** [comment]
> > Tested in the LFRic suite. All green: PSycloning, compilation, runs, style checks and KGO checks.
> 
> Hi @TeranIvy, was that with HEAD of PSyclone master?

Yes, @arporter, with the head of PSyclone master. I created a PSyclone branch from the head of master with the fparser submodule from this branch and then I installed PSyclone test environment from that.

**Comment by sergisiso** [comment]
@TeranIvy The last changes shouldn't change LFRic behavior but do touch the base classes that LFRic use. So it would be safer to test again.

**Review by rupertford — APPROVED** [review]
Changes look good. pylint and pycodestyle pass. No need to document at this point. Approving.

**Pull request merged**
